function setQuestion() {
	  var inputValue =  '{ "QUESTION" : [' +
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "0",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Practice Task", "QUESTIONCONTENT": "You can see the question here.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "1",  "PSEC" : "30",  "RSEC" : "90",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 1: Giving Advice", "QUESTIONCONTENT": "You can see the question here.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "2",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 2: Talking about a Personal Experience", "QUESTIONCONTENT": "You can see the question here.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "3",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_1.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 3: Describing a Scene", "QUESTIONCONTENT": "Describe some things that are happening in the picture below as well as you can. The person with whom you are speaking cannot see the picture.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "4",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_1.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 4: Making Predictions", "QUESTIONCONTENT": "In this picture, what do you think will most probably happen next?", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "5",  "PSEC" : "60",  "RSEC" : "0",  "IMG" : "picture/sample_2.jpeg",  "IMGCAPTION": "Option1: <br/>Explain it<br/>ex)-400$<br/>-<br/>-", "IMG2": "picture/sample_3.jpeg", "IMG2CAPTION": "Option2: <br/>Explain it<br/>ex)-500$<br/>-<br/>-", "IMG3": "picture/sample_4.jpeg", "IMG3CAPTION": "Your familly choice: <br/>Explain it<br/>ex)-400$<br/>-<br/>-", "QUESTIONTITLE": "Speaking Task 5: Comparing and Persuading", "QUESTIONCONTENT": "Explain the situation and you have to choice one of these options.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "Using the pictures and information below, choose the option that you prefer. In the next section, you will need to persuade a familly member that your choice is the better choice." },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "6",  "PSEC" : "60",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 6: Dealing with a Difficult Situation", "QUESTIONCONTENT": "Explain the difficult situation here.", "QUESTIONCONTENTEXTRA": "Choose ONE: <br/>EITHER<br/>Option 1<br/>OR<br/>Option 2", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "7",  "PSEC" : "30",  "RSEC" : "90",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 7: Expressing Opinions", "QUESTIONCONTENT": "Ask about your experience", "QUESTIONCONTENTEXTRA": "Please register your question.", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "8",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_5.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 8: Describing an Unusual Situation", "QUESTIONCONTENT": "Explain the unusual situation.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" }'+ 
	  ']}';

	var objQuestion = JSON.parse(inputValue);
	return objQuestion;
}